Database cleanup scripts, PLATFORM-6441
Wikia/kratos pull request #56
Opened 2022-02-16 08:34 UTC by abador

## Related issue(s)

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

2022-02-22 12:02 UTC, harnash requested changes

2022-02-22 12:02 UTC, harnash commented on persistence/sql/persister_recovery.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
```suggestion
		"DELETE FROM `%s` WHERE `expires_at` <= ? LIMIT ?",
```

2022-02-22 12:02 UTC, harnash commented on persistence/sql/persister_registration.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
```suggestion
		"DELETE FROM `%s` WHERE `expires_at` <= ? LIMIT ?",
```

2022-02-22 12:02 UTC, harnash commented on persistence/sql/persister_session.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
```suggestion
		"DELETE FROM `%s` WHERE `expires_at` <= ? LIMIT ?",
```

2022-02-22 12:02 UTC, harnash commented on persistence/sql/persister_settings.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
```suggestion
		"DELETE FROM `%s` WHERE `expires_at` <= ? LIMIT ?",
```

2022-02-22 12:02 UTC, harnash commented on persistence/sql/persister_verification.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
```suggestion
		"DELETE FROM `%s` WHERE `expires_at` <= ? LIMIT ?",
```

2022-02-24 09:27 UTC, abador commented on cmd/cleanup/sql.go
> +		Use:   "sql <database-url>",
it's the same as NewMigrateSQLCmd

2022-02-24 09:30 UTC, abador commented on cmd/cleanup/sql.go
> +	c.Flags().BoolP("read-from-env", "e", false, "If set, reads the database connection string from the environment variable DSN or config file key dsn.")
I was thinking about leaving only the batch size param (I'll rename it from cleanup limit), with sleep set statically to one minute there is still time for the replicas to catch up. But I'll add config for that

2022-02-25 09:44 UTC, abador commented on cmd/cleanup/sql.go
> +	c.Flags().BoolP("read-from-env", "e", false, "If set, reads the database connection string from the environment variable DSN or config file key dsn.")
since this code is being run via a background task and command line I'll leave the params on the config side

2022-02-28 07:51 UTC, abador commented on cmd/daemon/serve.go
> +		go cleanup.BackgroundCleanup(ctx, d)
This is prepared for single node setups. We don't need to enable this

2022-02-28 07:54 UTC, abador commented on persistence/sql/persister_continuity.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
I kept the style of the queries the same as in upstream. Let's create a discussion about this and check if they want to change this

2022-02-28 07:55 UTC, abador commented on persistence/sql/persister_login.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
the same as the comment above

2022-02-28 07:55 UTC, abador commented on persistence/sql/persister_recovery.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
the same as the comment above

2022-02-28 07:55 UTC, abador commented on persistence/sql/persister_registration.go
> +		"DELETE FROM %s WHERE expires_at <= ? LIMIT ?",
the same as the comment above

2022-02-28 08:39 UTC, abador commented on cmd/cleanup/sql.go
> +	c.Flags().BoolP("read-from-env", "e", false, "If set, reads the database connection string from the environment variable DSN or config file key dsn.")
Ok so there will be two config values for the background

2022-03-08 14:37 UTC, merged