Strip url param from config, PLATFORM-7016
Wikia/kratos pull request #61
Opened 2022-04-13 10:32 UTC by abador

## Related issue(s)

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

2022-04-14 15:59 UTC, harnash requested changes

2022-04-14 15:59 UTC, harnash commented on x/clean_url.go
> +			fmt.Println(prefix)
;-)
```suggestion
```

2022-04-14 15:59 UTC, harnash commented on x/clean_url.go
> +				fmt.Println(r.URL.Path)
```suggestion
```

2022-04-27 06:55 UTC, abador commented
We'll do it using nginx

2022-04-27 06:55 UTC, closed without merging